### ISSUE TITLE
上周日学校更新了统一登陆界面，现在每次登陆都要输验证码

### ISSUE THREAD

**Issue by leukocyte-yh** [Vizards/uestc-react-native-ios#15]
现在用这个app不能直接登陆啊，求修复

**Comment by Vizards** [comment]
@leukocyte-yh 正在修

**Comment by Vizards** [comment]
😓今天发现学校又改回来了，不需要验证码了，但是登录页面的 cookies 获取和携带要求全变了。

先等等看吧，看他们还要怎么改，省得做无用功

因为服务器的 IP 被学校封禁，所以我把 App 服务端停了，所以暂时 App 无法使用，抱歉了

**Comment by Vizards** [comment]
App 暂时恢复，但是需要重新登录。
为解决学校封禁服务器 IP 问题，接下来仍将对服务端进行更新和测试，测试期间服务可能不稳定。
相关更新内容：

https://github.com/Vizards/uestc-api/issues/3

**Comment by leukocyte-yh** [comment]
刚才试了一下，可以用了。感谢大佬

**Comment by leuk0cyte** [comment]
大佬，什么时候能更新啊，之前学校更新了登陆界面，现在app登录不了

**Comment by Vizards** [comment]
@leukocyte-yh 最近在调整接口和域名，会尽快

PS.发现新问题请开新issue，在已关闭的issue里回复我可能看不到
